volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres:14
    command: postgres -c 'max_connections=500'
    restart: always
    container_name: cinemadraft-postgres-nextjs
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 60s
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.local
  #     args:
  #       NEXT_PUBLIC_API_BASE: /api
  #       NEXT_PUBLIC_MP_ID: 879066a234a61cab4f4df1bb60a8efd8
  #       NEXT_PUBLIC_SUPPORT_EMAIL: support@healiahealth.com
  #   container_name: nextjs
  #   restart: always
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   links:
  #     - db
