// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as AwardShowsRoute from "@/app/award-shows/page.info";
import * as BrowseRoute from "@/app/browse/page.info";
import * as RulesAndScoringRoute from "@/app/rules-and-scoring/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const AwardShows = makeRoute(
  "/award-shows",
  {
    ...defaultInfo,
    ...AwardShowsRoute.Route
  }
);
export const Browse = makeRoute(
  "/browse",
  {
    ...defaultInfo,
    ...BrowseRoute.Route
  }
);
export const RulesAndScoring = makeRoute(
  "/rules-and-scoring",
  {
    ...defaultInfo,
    ...RulesAndScoringRoute.Route
  }
);

