// @vitest-environment node

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';

import { db } from '@/lib/db';
import { movieRepository } from '@/lib/repositories/movies';
import { loadFixture } from '@/test/fixtures';
import { type FilmScoring, loadFilmPage } from './film';
import { getLeaderboard } from './leaderboard';
import { getLeagueBoardView, type LeagueBoardView } from './league-view';

vi.mock('@/lib/external/omdb', () => ({ fetchOmdb: async () => null }));
vi.mock('@/lib/external/tmdb-film', () => ({
  fetchTmdbFilmPage: async (tmdbId: string) => ({
    tmdbId,
    imdbId: null,
    title: tmdbId,
    year: null,
    tagline: null,
    overview: null,
    runtimeMinutes: null,
    language: null,
    genres: [],
    releaseDate: null,
    budget: null,
    revenue: null,
    productionCompanies: [],
    backdropPath: null,
    posterPaths: [],
    trailers: [],
    cast: [],
    crew: [],
    similar: [],
  }),
}));

afterAll(async () => {
  await db.$disconnect();
});

/**
 * 🔴 The port against every figure the source app scored — restored data only,
 * so it is excluded from `vitest.ci.config.mts`.
 *
 * `test/scoring-differential.json` is the source's own `server/routes/points.js`
 * run over the dump this database was restored from (generated by
 * `scripts/capture-scoring-differential.cjs`, ids only): every film × season
 * and its per-show cells, every seat by draft id, every pick, every league
 * table's order and every film page. Each is compared exactly, and in order,
 * against the port's real services.
 *
 * The port departs from the source by two owner rulings, and only those:
 *
 * - **D125**, a win pays on the nomination that won. Its deviations are
 *   derived below in SQL from the nomination and winner rows — the by-film
 *   bonus the source paid, minus the by-nomination bonus the port pays — never
 *   typed in.
 * - **D126**, a pick counts only its own season's nominations. Its deviations
 *   are derived from the fixture itself: the source's value for a pick was the
 *   film's total over every season, and this test first proves that of the
 *   source's own numbers before relying on it.
 *
 * And by one data fix, which is not a ruling about scoring:
 *
 * - **D132**, duplicate film rows merged into the oldest. The source scored
 *   both rows of a pair; the port has one. A fixture film id that is no longer
 *   in `movies` folds into the surviving row with the same TMDB id, and that
 *   row is expected to carry the **sum** of both. The loser's TMDB id comes
 *   from the Heroku capture in `fixtures/` (every embedded film there carries
 *   its `id` and `tmdbId`), and the keeper from `movies` — never a hand list.
 *
 * Everything outside those lists must equal the source. Tie order is the
 * port's (draft order, D126); the source had none — its seat list came back in
 * whatever order Postgres returned, and two runs of it disagreed.
 *
 * 🔴 The fixture is frozen at the capture. If `.local/baseline.dump` is ever
 * refreshed with new nominations or winners, this goes red until the source is
 * re-captured against the matching dump.
 */
type Cells = Record<string, number>;
type Fixture = {
  counts: Record<string, number>;
  filmSeasons: [year: number, movieId: number, total: number, cells: Cells][];
  seats: [leagueId: number, year: number, draftId: number, total: number][];
  picks: [pickId: number, shown: number][];
  standings: [leagueId: number, year: number, draftIds: number[]][];
  filmPages: [tmdbId: string, total: number | null, avg: number | null, cells: Cells][];
};
const SOURCE = JSON.parse(
  readFileSync(join(process.cwd(), 'test/scoring-differential.json'), 'utf8'),
) as Fixture;

const key = (...parts: (number | string)[]) => parts.join('/');
const sum = (values: Iterable<number>) => [...values].reduce((a, b) => a + b, 0);

/** Competition rank of totals already in descending order: 1, 1, 3. */
const ranks = (totals: number[]) => totals.map((total) => totals.indexOf(total) + 1);

// Loaded once: the port's figures and both derivations.
const port = {
  boards: new Map<string, LeagueBoardView>(),
  leaderboards: new Map<number, Map<number, { total: number; cells: Cells }>>(),
  leaderboardTotals: new Map<number, number[]>(),
  films: new Map<string, { movieId: number | null; scoring: FilmScoring | null }>(),
};
/** D125: `year/movieId` → the port's figure minus the source's, and per show. */
const d125 = { film: new Map<string, number>(), cell: new Map<string, number>() };
/** The source's film × season totals: `year/movieId` → total. */
const source = new Map<string, number>();
const seasonsOf = new Map<number, number[]>();
let pickRows: { pickId: number; draftId: number; movieId: number; year: number }[] = [];
let draftRows: { id: number; userId: number | null; leagueId: number; year: number }[] =
  [];

/**
 * D132: the fixture's film ids with merged ones replaced by their keeper, and
 * a keeper's two figures in one season summed. Built in `beforeAll`.
 */
let filmSeasons: Fixture['filmSeasons'] = [];
/** D132: fixture film id → the id it folded into, for ids no longer in `movies`. */
const folded = new Map<number, number>();

/** `id → tmdbId` for every film the Heroku capture embeds. */
function capturedTmdbIds(): Map<number, string> {
  const found = new Map<number, string>();
  const walk = (node: unknown): void => {
    if (Array.isArray(node)) for (const item of node) walk(item);
    else if (node && typeof node === 'object') {
      const record = node as Record<string, unknown>;
      if (
        typeof record.id === 'number' &&
        typeof record.tmdbId === 'string' &&
        'title' in record
      )
        found.set(record.id, record.tmdbId);
      for (const value of Object.values(record)) walk(value);
    }
  };
  const dir = join(process.cwd(), 'fixtures');
  for (const file of readdirSync(dir).filter((name) => name.endsWith('.json')))
    walk(JSON.parse(readFileSync(join(dir, file), 'utf8')));
  return found;
}

async function foldMergedFilms() {
  const movies = await db.movie.findMany({ select: { id: true, tmdbId: true } });
  const present = new Set(movies.map((movie) => movie.id));
  const keeperOf = new Map(movies.map((movie) => [movie.tmdbId, movie.id]));
  const captured = capturedTmdbIds();
  for (const [, movieId] of SOURCE.filmSeasons) {
    if (present.has(movieId) || folded.has(movieId)) continue;
    const keeper = keeperOf.get(captured.get(movieId) ?? null);
    if (keeper === undefined)
      throw new Error(
        `fixture film ${movieId} is not in movies and has no merged keeper`,
      );
    folded.set(movieId, keeper);
  }
  const byKey = new Map<string, Fixture['filmSeasons'][number]>();
  for (const [year, movieId, total, cells] of SOURCE.filmSeasons) {
    const id = folded.get(movieId) ?? movieId;
    const seen = byKey.get(key(year, id));
    if (!seen) {
      byKey.set(key(year, id), [year, id, total, { ...cells }]);
      continue;
    }
    seen[2] += total;
    for (const [abbr, points] of Object.entries(cells))
      seen[3][abbr] = (seen[3][abbr] ?? 0) + points;
  }
  filmSeasons = [...byKey.values()];
}

beforeAll(async () => {
  await foldMergedFilms();
  for (const [year, movieId, total] of filmSeasons) {
    source.set(key(year, movieId), total);
    seasonsOf.set(movieId, [...(seasonsOf.get(movieId) ?? []), year]);
  }

  const rows = await db.$queryRaw<
    { movieId: number; year: number; abbreviation: string; delta: number }[]
  >`
    SELECT "movieId", year, abbreviation, delta FROM (
      SELECT n.movie_id::int AS "movieId", n.year, e.abbreviation,
             SUM(p.points * (
               (EXISTS (SELECT 1 FROM winners w
                         WHERE w.nomination_id = n.id AND w.year = n.year))::int
             - (EXISTS (SELECT 1 FROM winners w
                         WHERE w.award_id = n.award_id AND w.movie_id = n.movie_id
                           AND w.year = n.year))::int
             ))::int AS delta
        FROM nominations n
        JOIN awards a ON a.id = n.award_id
        JOIN points p ON p.id = a.points
        JOIN events e ON e.id = a.event_id
       GROUP BY 1, 2, 3
    ) cells WHERE delta <> 0`;
  for (const row of rows) {
    d125.cell.set(key(row.year, row.movieId, row.abbreviation), row.delta);
    const film = key(row.year, row.movieId);
    d125.film.set(film, (d125.film.get(film) ?? 0) + row.delta);
  }

  pickRows = await db.$queryRaw`
    SELECT p.id::int AS "pickId", p.draft_id::int AS "draftId", p.movie_id::int AS "movieId",
           d.year::int AS year
      FROM draft_picks p JOIN drafts d ON d.id = p.draft_id
     WHERE p.movie_id IS NOT NULL`;
  draftRows = await db.$queryRaw`
    SELECT id::int AS id, user_id::int AS "userId", league_id::int AS "leagueId",
           year::int AS year FROM drafts`;

  for (const [leagueId, year] of SOURCE.standings) {
    port.boards.set(key(leagueId, year), await getLeagueBoardView(leagueId, year, null));
  }
  for (const year of new Set(filmSeasons.map(([y]) => y))) {
    const board = await getLeaderboard(year);
    port.leaderboards.set(
      year,
      new Map(
        board.rows.map((row) => [row.movieId, { total: row.total, cells: row.events }]),
      ),
    );
    port.leaderboardTotals.set(
      year,
      board.rows.map((row) => row.total),
    );
  }
  for (const [tmdbId] of SOURCE.filmPages) {
    const [page, movie] = await Promise.all([
      loadFilmPage(tmdbId),
      movieRepository.findByTmdbId(tmdbId),
    ]);
    port.films.set(tmdbId, {
      movieId: movie?.id ?? null,
      scoring: page?.scoring ?? null,
    });
  }
}, 600_000);

/** What the port should show for a film in a season: the source's, plus D125. */
const expectedFilm = (year: number, movieId: number) =>
  (source.get(key(year, movieId)) ?? 0) + (d125.film.get(key(year, movieId)) ?? 0);

/** D126 for one pick: the other seasons the source added in. */
const d126 = (movieId: number, year: number) =>
  -sum(
    (seasonsOf.get(movieId) ?? [])
      .filter((s) => s !== year)
      .map((s) => source.get(key(s, movieId)) ?? 0),
  );

describe('the fixture', () => {
  it('holds every figure the audit compared', () => {
    expect(SOURCE.counts).toEqual({
      filmSeasons: 1109,
      seats: 156,
      picks: 1025,
      standings: 20,
      filmPages: 1100,
    });
  });

  it('matches what the live site answered for league 1 in 2025', () => {
    // An anchor outside the audit's run: `fixtures/points-league-total.json`
    // was captured from the live Heroku API. Its names are scrubbed, so only
    // the totals, highest first, can be compared — which is why the seat-by-
    // seat comparison below needs this fixture's draft ids.
    const live = loadFixture<{ total: number }[]>('points-league-total');
    const [, , order] = SOURCE.standings.find(([l, y]) => l === 1 && y === 2025) ?? [];
    const total = new Map(
      SOURCE.seats.filter(([l, y]) => l === 1 && y === 2025).map(([, , d, t]) => [d, t]),
    );
    expect(order?.map((draftId) => total.get(draftId))).toEqual(
      live.map((row) => row.total),
    );
  });

  it('bears out the D126 derivation on the source’s own numbers', () => {
    // A source pick was worth its film's total over EVERY season. Proven here
    // for all 1,025 picks from two independent source endpoints — the explore
    // view and the season grid — before the deviation list relies on it.
    const byPick = new Map(pickRows.map((row) => [row.pickId, row]));
    const wrong = SOURCE.picks.filter(([pickId, shown]) => {
      const movieId = byPick.get(pickId)?.movieId as number;
      return (
        shown !==
        sum((seasonsOf.get(movieId) ?? []).map((s) => source.get(key(s, movieId)) ?? 0))
      );
    });
    expect(wrong).toEqual([]);
  });
});

describe('the port against the source', () => {
  it('scores every film × season and every per-show cell, D125 aside', () => {
    const wrong: unknown[] = [];
    let cells = 0;
    for (const [year, movieId, total, sourceCells] of filmSeasons) {
      const ours = port.leaderboards.get(year)?.get(movieId);
      if (ours?.total !== expectedFilm(year, movieId))
        wrong.push({ year, movieId, source: total, ours: ours?.total });
      const shows = new Set([
        ...Object.keys(sourceCells),
        ...Object.entries(ours?.cells ?? {}).flatMap(([abbr, v]) =>
          v === 0 ? [] : [abbr],
        ),
      ]);
      for (const abbr of shows) {
        cells += 1;
        const expected =
          (sourceCells[abbr] ?? 0) + (d125.cell.get(key(year, movieId, abbr)) ?? 0);
        if ((ours?.cells[abbr] ?? 0) !== expected)
          wrong.push({ year, movieId, abbr, expected, ours: ours?.cells[abbr] });
      }
    }
    expect(wrong).toEqual([]);
    // Same films, and each season's rows run highest first. (Which of two
    // tied films lists first is display only, D11.)
    for (const [year, rows] of port.leaderboards) {
      const sourceIds = filmSeasons.filter(([y]) => y === year).map(([, id]) => id);
      expect({ year, films: [...rows.keys()].sort() }).toEqual({
        year,
        films: sourceIds.sort(),
      });
      const totals = port.leaderboardTotals.get(year) ?? [];
      expect(totals).toEqual([...totals].sort((a, b) => b - a));
    }
    // 2,542 nonzero cells on the restored data; zero-filled ones say nothing.
    expect(cells).toBeGreaterThan(2500);
  });

  it('values every pick as the source did, D125 and D126 aside', () => {
    const ours = new Map(
      [...port.boards.values()].flatMap((view) =>
        view.groups.flatMap((g) =>
          g.seats.flatMap((s) => s.picks.map((p) => [p.pickId, p.points])),
        ),
      ),
    );
    const byPick = new Map(pickRows.map((row) => [row.pickId, row]));
    const wrong = SOURCE.picks.flatMap(([pickId, shown]) => {
      const { movieId, year } = byPick.get(pickId) as { movieId: number; year: number };
      const expected =
        shown + d126(movieId, year) + (d125.film.get(key(year, movieId)) ?? 0);
      return ours.get(pickId) === expected
        ? []
        : [{ pickId, shown, expected, ours: ours.get(pickId) }];
    });
    expect(wrong).toEqual([]);
    expect(ours.size).toBe(SOURCE.picks.length);
  });

  it('totals every seat by draft id, D125 and D126 aside', () => {
    const wrong = SOURCE.seats.flatMap(([leagueId, year, draftId, total]) => {
      const seat = port.boards
        .get(key(leagueId, year))
        ?.groups.flatMap((g) => g.seats)
        .find((s) => s.draftId === draftId);
      const expected = total + seatDelta(draftId, year);
      return seat?.total === expected
        ? []
        : [{ leagueId, year, draftId, total, expected, ours: seat?.total }];
    });
    expect(wrong).toEqual([]);
    const seats = [...port.boards.values()].flatMap((v) =>
      v.groups.flatMap((g) => g.seats),
    );
    expect(seats.length).toBe(SOURCE.seats.length);
  });

  it('orders and numbers every league table as the source’s totals demand', () => {
    // 🔴 Ordered: a swap of any two seats fails, including two tied ones.
    for (const [leagueId, year, sourceOrder] of SOURCE.standings) {
      const view = port.boards.get(key(leagueId, year)) as LeagueBoardView;
      const drafted = view.groups.flatMap((g) => g.seats.map((s) => s.draftId));
      const total = new Map(
        SOURCE.seats
          .filter(([l, y]) => l === leagueId && y === year)
          .map(([, , draftId, t]) => [draftId, t + seatDelta(draftId, year)]),
      );
      const order = [...sourceOrder].sort(
        (a, b) =>
          (total.get(b) as number) - (total.get(a) as number) ||
          drafted.indexOf(a) - drafted.indexOf(b),
      );
      const totals = order.map((d) => total.get(d) as number);
      const expected = order.map((draftId, i) => ({
        draftId,
        total: totals[i],
        position: ranks(totals)[i],
      }));

      const ours = view.standings.map((row) => ({
        draftId: row.userId < 0 ? -row.userId : draftOf(leagueId, year, row.userId),
        total: row.total,
        position: row.position,
      }));
      expect({ leagueId, year, standings: ours }).toEqual({
        leagueId,
        year,
        standings: expected,
      });
    }
  });

  it('shows every film page’s seasons separately, D125 and D126 aside', () => {
    const wrong: unknown[] = [];
    for (const [tmdbId, total, avg, cells] of SOURCE.filmPages) {
      const { movieId, scoring } = port.films.get(tmdbId) ?? {
        movieId: null,
        scoring: null,
      };
      const years =
        movieId == null ? [] : [...(seasonsOf.get(movieId) ?? [])].sort((a, b) => b - a);
      const expected = years.map((year) => ({
        year,
        total: expectedFilm(year, movieId as number),
      }));
      const seasons =
        scoring?.seasons.map(({ year, total: t }) => ({ year, total: t })) ?? [];
      if (JSON.stringify(seasons) !== JSON.stringify(expected))
        wrong.push({ tmdbId, expected, seasons });

      // The source's one figure is every season summed (D126 is what splits
      // it); each show's cells likewise.
      // D132: the source's page read one row of a duplicated film; the port's
      // reads the merged one, so the rows that page never saw are added in.
      const extra = movieId == null ? NONE : unseenRows(movieId, total, cells);
      if (total !== null) {
        const summed = sum(years.map((y) => source.get(key(y, movieId as number)) ?? 0));
        if (summed !== total + extra.total)
          wrong.push({ tmdbId, sourceTotal: total, d132: extra.total, summed });
      }
      const shows: Cells = {};
      for (const season of scoring?.seasons ?? [])
        for (const event of season.byEvent)
          shows[event.abbreviation] =
            (shows[event.abbreviation] ?? 0) +
            event.total -
            (d125.cell.get(key(season.year, movieId as number, event.abbreviation)) ?? 0);
      const nonzero = Object.fromEntries(
        Object.entries(shows).filter(([, v]) => v !== 0),
      );
      const expectedCells = addCells(cells, extra.cells);
      if (
        JSON.stringify(Object.entries(nonzero).sort()) !==
        JSON.stringify(Object.entries(expectedCells).sort())
      )
        wrong.push({ tmdbId, cells: expectedCells, ours: nonzero });
      // Null where nobody drafted it; the source printed 0 (PARITY, D9).
      if ((scoring?.averageDraftPosition ?? 0) !== (avg ?? 0) && scoring !== null)
        wrong.push({ tmdbId, avg, ours: scoring?.averageDraftPosition });
    }
    expect(wrong).toEqual([]);
  });
});

describe('the deviations, derived', () => {
  // Sized against the audit's own measurements (.context/scoring-audit.md §4,
  // §6). A derivation that went quietly empty would let everything pass.
  it('D125 moves nine film-seasons', () => {
    expect(d125.film.size).toBe(9);
  });

  it('D132 folds the four merged films that carry nominations', () => {
    // Allegiant, Ready Player One, Solo and My Life as a Zucchini: the only
    // merged pairs whose losing row was ever nominated.
    expect([...folded.entries()].sort(([a], [b]) => a - b)).toEqual([
      [117, 50],
      [177, 60],
      [331, 270],
      [332, 258],
    ]);
  });

  it('D126 moves seven picks, seven seats and splits six film pages', () => {
    const byPick = new Map(pickRows.map((row) => [row.pickId, row]));
    const picks = SOURCE.picks.filter(([pickId]) => {
      const { movieId, year } = byPick.get(pickId) as { movieId: number; year: number };
      return d126(movieId, year) !== 0;
    });
    const seats = SOURCE.seats.filter(([, year, draftId]) =>
      pickRows.some((p) => p.draftId === draftId && d126(p.movieId, year) !== 0),
    );
    // Counted on the keeper's own seasons, before D132's fold: a merged pair
    // whose two rows were nominated in different years is D132's split, not
    // D126's.
    const pages = SOURCE.filmPages.filter(([tmdbId]) => {
      const movieId = port.films.get(tmdbId)?.movieId;
      return (
        movieId != null &&
        SOURCE.filmSeasons.filter(([, id]) => id === movieId).length > 1
      );
    });

    expect(picks.map(([id]) => id).sort((a, b) => a - b)).toEqual([
      140, 188, 427, 491, 685, 708, 713,
    ]);
    expect(seats.map(([, , id]) => id).sort((a, b) => a - b)).toEqual([
      20, 27, 60, 68, 96, 99, 100,
    ]);
    expect(pages).toHaveLength(6);
  });
});

const NONE = { total: 0, cells: {} as Cells };

function addCells(a: Cells, b: Cells): Cells {
  const out: Cells = { ...a };
  for (const [abbr, points] of Object.entries(b)) out[abbr] = (out[abbr] ?? 0) + points;
  return Object.fromEntries(Object.entries(out).filter(([, v]) => v !== 0));
}

/**
 * D132 on a film page: the fixture rows folded into `keeper` that the source's
 * page for that film did not count. The page read one row of a pair; which one
 * is found by matching the page's total and cells against each row's own
 * figures, so nothing is assumed about the source's choice.
 */
function unseenRows(keeper: number, pageTotal: number | null, pageCells: Cells) {
  const rows = [keeper, ...[...folded].filter(([, k]) => k === keeper).map(([id]) => id)];
  if (rows.length === 1) return NONE;
  const own = rows.map((id) => {
    const seasons = SOURCE.filmSeasons.filter(([, movieId]) => movieId === id);
    return {
      id,
      total: sum(seasons.map(([, , t]) => t)),
      cells: seasons.reduce<Cells>((acc, [, , , c]) => addCells(acc, c), {}),
    };
  });
  const seen = own.find(
    (row) =>
      row.total === (pageTotal ?? 0) &&
      JSON.stringify(Object.entries(row.cells).sort()) ===
        JSON.stringify(Object.entries(pageCells).sort()),
  );
  if (!seen) throw new Error(`film ${keeper}: the source page matches none of its rows`);
  return own
    .filter((row) => row !== seen)
    .reduce(
      (acc, row) => ({
        total: acc.total + row.total,
        cells: addCells(acc.cells, row.cells),
      }),
      NONE,
    );
}

/** A seat's move under both rulings: the sum over its picks. */
function seatDelta(draftId: number, year: number): number {
  return sum(
    pickRows
      .filter((p) => p.draftId === draftId)
      .map((p) => d126(p.movieId, year) + (d125.film.get(key(year, p.movieId)) ?? 0)),
  );
}

function draftOf(leagueId: number, year: number, userId: number): number {
  const seats = draftRows.filter(
    (d) => d.leagueId === leagueId && d.year === year && d.userId === userId,
  );
  if (seats.length !== 1) throw new Error(`user ${userId} holds ${seats.length} seats`);
  return (seats[0] as { id: number }).id;
}
