-- Generated by scripts/generate-normalize-sql.mjs (D27). Do not hand-edit.
-- Regenerate after any schema change, and re-apply after the cutover re-dump.
--
-- ALTER ... RENAME is a catalog operation: no row is read, written or moved,
-- so this cannot silently mismap data the way a rewritten dump file could.
-- Row counts are compared before and after to prove exactly that.

BEGIN;

-- 1. Drop dead objects (D27).
--    SequelizeMeta is the old ORM migration ledger, replaced by Prisma.
--    password and salt are NULL for every user and unpopulatable under
--    passwordless auth (D26) — carrying dead credential columns forward
--    is the kind of thing a later audit rightly asks about.
DROP TABLE IF EXISTS "SequelizeMeta";
ALTER TABLE "Users" DROP COLUMN IF EXISTS "password";
ALTER TABLE "Users" DROP COLUMN IF EXISTS "salt";

-- Users_uuid duplicates the index already backing Users_uuid_key.
DROP INDEX IF EXISTS "Users_uuid";

-- 2. Enum types.
ALTER TYPE "enum_Leagues_draftingStatus" RENAME TO "enum_leagues_drafting_status";
ALTER TYPE "enum_Leagues_type" RENAME TO "enum_leagues_type";
ALTER TYPE "enum_Lists_status" RENAME TO "enum_lists_status";
ALTER TYPE "enum_Users_role" RENAME TO "enum_users_role";

-- 3. Columns. Table names are still PascalCase at this point; tables are
--    renamed last so every statement above can address them unambiguously.
-- AvailableYears
ALTER TABLE "AvailableYears" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "AvailableYears" RENAME COLUMN "updatedAt" TO "updated_at";
-- Awards
ALTER TABLE "Awards" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Awards" RENAME COLUMN "eventId" TO "event_id";
ALTER TABLE "Awards" RENAME COLUMN "requiresNomineeName" TO "requires_nominee_name";
ALTER TABLE "Awards" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Awards" RENAME COLUMN "updatedAt" TO "updated_at";
-- DraftPicks
ALTER TABLE "DraftPicks" RENAME COLUMN "draftId" TO "draft_id";
ALTER TABLE "DraftPicks" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "DraftPicks" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "DraftPicks" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "DraftPicks" RENAME COLUMN "updatedAt" TO "updated_at";
-- Drafts
ALTER TABLE "Drafts" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Drafts" RENAME COLUMN "leagueId" TO "league_id";
ALTER TABLE "Drafts" RENAME COLUMN "dummyName" TO "dummy_name";
ALTER TABLE "Drafts" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Drafts" RENAME COLUMN "updatedAt" TO "updated_at";
-- Events
ALTER TABLE "Events" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Events" RENAME COLUMN "liveResults" TO "live_results";
ALTER TABLE "Events" RENAME COLUMN "nomActive" TO "nom_active";
ALTER TABLE "Events" RENAME COLUMN "nomDate" TO "nom_date";
ALTER TABLE "Events" RENAME COLUMN "nomTime" TO "nom_time";
ALTER TABLE "Events" RENAME COLUMN "nomDuration" TO "nom_duration";
ALTER TABLE "Events" RENAME COLUMN "awardsActive" TO "awards_active";
ALTER TABLE "Events" RENAME COLUMN "awardsDate" TO "awards_date";
ALTER TABLE "Events" RENAME COLUMN "awardsTime" TO "awards_time";
ALTER TABLE "Events" RENAME COLUMN "awardsDuration" TO "awards_duration";
ALTER TABLE "Events" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Events" RENAME COLUMN "updatedAt" TO "updated_at";
-- Leagues
ALTER TABLE "Leagues" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Leagues" RENAME COLUMN "activeYear" TO "active_year";
ALTER TABLE "Leagues" RENAME COLUMN "draftingStatus" TO "drafting_status";
ALTER TABLE "Leagues" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Leagues" RENAME COLUMN "updatedAt" TO "updated_at";
-- Lists
ALTER TABLE "Lists" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Lists" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "Lists" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Lists" RENAME COLUMN "updatedAt" TO "updated_at";
-- Movies
ALTER TABLE "Movies" RENAME COLUMN "sortTitle" TO "sort_title";
ALTER TABLE "Movies" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Movies" RENAME COLUMN "imdbId" TO "imdb_id";
ALTER TABLE "Movies" RENAME COLUMN "tmdbId" TO "tmdb_id";
ALTER TABLE "Movies" RENAME COLUMN "releaseDate" TO "release_date";
ALTER TABLE "Movies" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Movies" RENAME COLUMN "updatedAt" TO "updated_at";
-- Nominations
ALTER TABLE "Nominations" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Nominations" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "Nominations" RENAME COLUMN "awardId" TO "award_id";
ALTER TABLE "Nominations" RENAME COLUMN "detailName" TO "detail_name";
ALTER TABLE "Nominations" RENAME COLUMN "detailCharacter" TO "detail_character";
ALTER TABLE "Nominations" RENAME COLUMN "detailId" TO "detail_id";
ALTER TABLE "Nominations" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Nominations" RENAME COLUMN "updatedAt" TO "updated_at";
-- Notifications
ALTER TABLE "Notifications" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Notifications" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Notifications" RENAME COLUMN "updatedAt" TO "updated_at";
-- Points
ALTER TABLE "Points" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Points" RENAME COLUMN "updatedAt" TO "updated_at";
-- ProfileFeeds
ALTER TABLE "ProfileFeeds" RENAME COLUMN "userUuid" TO "user_uuid";
ALTER TABLE "ProfileFeeds" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "ProfileFeeds" RENAME COLUMN "updatedAt" TO "updated_at";
-- Reviews
ALTER TABLE "Reviews" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Reviews" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "Reviews" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Reviews" RENAME COLUMN "updatedAt" TO "updated_at";
-- Users
ALTER TABLE "Users" RENAME COLUMN "firstName" TO "first_name";
ALTER TABLE "Users" RENAME COLUMN "lastName" TO "last_name";
ALTER TABLE "Users" RENAME COLUMN "providerId" TO "provider_id";
ALTER TABLE "Users" RENAME COLUMN "lastLogin" TO "last_login";
ALTER TABLE "Users" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Users" RENAME COLUMN "updatedAt" TO "updated_at";
-- Watchlists
ALTER TABLE "Watchlists" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "Watchlists" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "Watchlists" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Watchlists" RENAME COLUMN "updatedAt" TO "updated_at";
-- Winners
ALTER TABLE "Winners" RENAME COLUMN "fbId" TO "fb_id";
ALTER TABLE "Winners" RENAME COLUMN "movieId" TO "movie_id";
ALTER TABLE "Winners" RENAME COLUMN "awardId" TO "award_id";
ALTER TABLE "Winners" RENAME COLUMN "nominationId" TO "nomination_id";
ALTER TABLE "Winners" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "Winners" RENAME COLUMN "updatedAt" TO "updated_at";

-- 4. Constraints. Renaming a constraint also renames the index backing it.
ALTER TABLE "AvailableYears" RENAME CONSTRAINT "AvailableYears_pkey" TO "available_years_pkey";
ALTER TABLE "AvailableYears" RENAME CONSTRAINT "AvailableYears_year_key" TO "available_years_year_key";
ALTER TABLE "Awards" RENAME CONSTRAINT "Awards_pkey" TO "awards_pkey";
ALTER TABLE "DraftPicks" RENAME CONSTRAINT "DraftPicks_pkey" TO "draft_picks_pkey";
ALTER TABLE "Drafts" RENAME CONSTRAINT "Drafts_pkey" TO "drafts_pkey";
ALTER TABLE "Events" RENAME CONSTRAINT "Events_pkey" TO "events_pkey";
ALTER TABLE "Leagues" RENAME CONSTRAINT "Leagues_pkey" TO "leagues_pkey";
ALTER TABLE "Lists" RENAME CONSTRAINT "Lists_pkey" TO "lists_pkey";
ALTER TABLE "Movies" RENAME CONSTRAINT "Movies_pkey" TO "movies_pkey";
ALTER TABLE "Nominations" RENAME CONSTRAINT "Nominations_pkey" TO "nominations_pkey";
ALTER TABLE "Notifications" RENAME CONSTRAINT "Notifications_pkey" TO "notifications_pkey";
ALTER TABLE "Points" RENAME CONSTRAINT "Points_pkey" TO "points_pkey";
ALTER TABLE "ProfileFeeds" RENAME CONSTRAINT "ProfileFeeds_pkey" TO "profile_feeds_pkey";
ALTER TABLE "Reviews" RENAME CONSTRAINT "Reviews_pkey" TO "reviews_pkey";
ALTER TABLE "Users" RENAME CONSTRAINT "Users_email_key" TO "users_email_key";
ALTER TABLE "Users" RENAME CONSTRAINT "Users_pkey" TO "users_pkey";
ALTER TABLE "Users" RENAME CONSTRAINT "Users_uuid_key" TO "users_uuid_key";
ALTER TABLE "Watchlists" RENAME CONSTRAINT "Watchlists_pkey" TO "watchlists_pkey";
ALTER TABLE "Winners" RENAME CONSTRAINT "Winners_pkey" TO "winners_pkey";

-- 5. Indexes not backed by a constraint.
ALTER INDEX "Awards_eventId" RENAME TO "awards_event_id";
ALTER INDEX "DraftPicks_draftId" RENAME TO "draft_picks_draft_id";
ALTER INDEX "DraftPicks_movieId" RENAME TO "draft_picks_movie_id";
ALTER INDEX "Drafts_leagueId" RENAME TO "drafts_league_id";
ALTER INDEX "Drafts_userId" RENAME TO "drafts_user_id";
ALTER INDEX "Drafts_year" RENAME TO "drafts_year";
ALTER INDEX "Events_abbreviation" RENAME TO "events_abbreviation";
ALTER INDEX "Events_nomDate_awardsDate" RENAME TO "events_nom_date_awards_date";
ALTER INDEX "Lists_userId" RENAME TO "lists_user_id";
ALTER INDEX "Lists_year" RENAME TO "lists_year";
ALTER INDEX "Movies_tmdbId" RENAME TO "movies_tmdb_id";
ALTER INDEX "Nominations_awardId" RENAME TO "nominations_award_id";
ALTER INDEX "Nominations_movieId" RENAME TO "nominations_movie_id";
ALTER INDEX "Nominations_year" RENAME TO "nominations_year";
ALTER INDEX "Notifications_userId" RENAME TO "notifications_user_id";
ALTER INDEX "ProfileFeeds_userUuid" RENAME TO "profile_feeds_user_uuid";
ALTER INDEX "Reviews_movieId" RENAME TO "reviews_movie_id";
ALTER INDEX "Reviews_userId" RENAME TO "reviews_user_id";
ALTER INDEX "Users_providerId" RENAME TO "users_provider_id";
ALTER INDEX "Watchlists_userId" RENAME TO "watchlists_user_id";
ALTER INDEX "Winners_awardId" RENAME TO "winners_award_id";
ALTER INDEX "Winners_movieId" RENAME TO "winners_movie_id";
ALTER INDEX "Winners_nominationId" RENAME TO "winners_nomination_id";
ALTER INDEX "Winners_year" RENAME TO "winners_year";

-- 6. Sequences. Column defaults store the sequence as an OID, not as text,
--    so the nextval() defaults follow the rename automatically.
ALTER SEQUENCE "AvailableYears_id_seq" RENAME TO "available_years_id_seq";
ALTER SEQUENCE "Awards_id_seq" RENAME TO "awards_id_seq";
ALTER SEQUENCE "DraftPicks_id_seq" RENAME TO "draft_picks_id_seq";
ALTER SEQUENCE "Drafts_id_seq" RENAME TO "drafts_id_seq";
ALTER SEQUENCE "Events_id_seq" RENAME TO "events_id_seq";
ALTER SEQUENCE "Leagues_id_seq" RENAME TO "leagues_id_seq";
ALTER SEQUENCE "Lists_id_seq" RENAME TO "lists_id_seq";
ALTER SEQUENCE "Movies_id_seq" RENAME TO "movies_id_seq";
ALTER SEQUENCE "Nominations_id_seq" RENAME TO "nominations_id_seq";
ALTER SEQUENCE "Notifications_id_seq" RENAME TO "notifications_id_seq";
ALTER SEQUENCE "Points_id_seq" RENAME TO "points_id_seq";
ALTER SEQUENCE "ProfileFeeds_id_seq" RENAME TO "profile_feeds_id_seq";
ALTER SEQUENCE "Reviews_id_seq" RENAME TO "reviews_id_seq";
ALTER SEQUENCE "Users_id_seq" RENAME TO "users_id_seq";
ALTER SEQUENCE "Watchlists_id_seq" RENAME TO "watchlists_id_seq";
ALTER SEQUENCE "Winners_id_seq" RENAME TO "winners_id_seq";

-- 7. Tables, last.
ALTER TABLE "AvailableYears" RENAME TO "available_years";
ALTER TABLE "Awards" RENAME TO "awards";
ALTER TABLE "DraftPicks" RENAME TO "draft_picks";
ALTER TABLE "Drafts" RENAME TO "drafts";
ALTER TABLE "Events" RENAME TO "events";
ALTER TABLE "Leagues" RENAME TO "leagues";
ALTER TABLE "Lists" RENAME TO "lists";
ALTER TABLE "Movies" RENAME TO "movies";
ALTER TABLE "Nominations" RENAME TO "nominations";
ALTER TABLE "Notifications" RENAME TO "notifications";
ALTER TABLE "Points" RENAME TO "points";
ALTER TABLE "ProfileFeeds" RENAME TO "profile_feeds";
ALTER TABLE "Reviews" RENAME TO "reviews";
ALTER TABLE "Users" RENAME TO "users";
ALTER TABLE "Watchlists" RENAME TO "watchlists";
ALTER TABLE "Winners" RENAME TO "winners";

COMMIT;

